# Generated by Django 3.2.5 on 2021-07-14 23:29

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Title', unique=True)),
                ('Price', models.FloatField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Img', models.ImageField(upload_to='pics')),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
