# Generated by Django 3.2.5 on 2021-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
    ]
